version: "2.0.0"
slug: "stt"
name: "Speech-to-text API"
description: "Speech-to-text via an external API"
url: "https://github.com/VernonVega/wyoming-stt-api-addon/tree/main/wyoming_stt_api"
arch:
  - aarch64
  - amd64
init: false
ports:
  10300/tcp: 10300
options:
  ats_url: null
  max_audio_duration_s: 10
schema:
  ats_url: str
  max_audio_duration_s: int
